apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: recipes
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/recipes
  JWT_SECRET: super-secret-key
